
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 1234
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_grupo = new javax.swing.ButtonGroup();
        rb_grupoP = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_nombreP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t_edadP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rb_fP = new javax.swing.JRadioButton();
        rb_mP = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        t_estadoCivilP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t_ocupacion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_hE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t_hS = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        c_fechaP = new com.toedter.calendar.JDateChooser();
        bt_guardarP = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        t_sueldoP = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        t_contraseñaP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rb_f = new javax.swing.JRadioButton();
        rb_m = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        t_estadoCivil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_rolles = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        t_trabajo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_altura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_peso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_objetos = new javax.swing.JComboBox<>();
        bt_guardarF = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        t_contraseña = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bt_color = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        t_marca = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t_tamano = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        t_calidad = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        t_precio = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        t_confort = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        t_paisElaboracion = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        t_suela = new javax.swing.JTextField();
        bt_Ropa = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        t_tallaZ = new javax.swing.JTextField();
        t_tiempoVida = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        t_material = new javax.swing.JTextField();
        bt_zapatos1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        t_tallaRopa = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        cb_area = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_descripcion1 = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        c_fechaObjeto = new com.toedter.calendar.JDateChooser();
        bt_guardarHogar = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        cb_dueño = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        t_nombre1 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        t_edad1 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        rb_f1 = new javax.swing.JRadioButton();
        rb_m1 = new javax.swing.JRadioButton();
        jLabel59 = new javax.swing.JLabel();
        t_estadoCivil1 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        cb_rolles1 = new javax.swing.JComboBox<>();
        jLabel61 = new javax.swing.JLabel();
        t_trabajo1 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        t_altura1 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        t_peso1 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        cb_objetos1 = new javax.swing.JComboBox<>();
        bt_guardarF1 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        t_contraseña1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        bt_color1 = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_descripcion2 = new javax.swing.JTextArea();
        jLabel69 = new javax.swing.JLabel();
        t_marca1 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        t_tamano1 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        t_calidad1 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        t_precio1 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        t_confort1 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        t_paisElaboracion1 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        t_suela1 = new javax.swing.JTextField();
        bt_Ropa1 = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        t_tallaZ1 = new javax.swing.JTextField();
        t_tiempoVida1 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        t_material1 = new javax.swing.JTextField();
        bt_zapatos2 = new javax.swing.JButton();
        jLabel82 = new javax.swing.JLabel();
        t_tallaRopa1 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        cb_area1 = new javax.swing.JComboBox<>();
        jLabel84 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_descripcion3 = new javax.swing.JTextArea();
        jLabel85 = new javax.swing.JLabel();
        c_fechaObjeto1 = new com.toedter.calendar.JDateChooser();
        bt_guardarHogar1 = new javax.swing.JButton();
        jLabel86 = new javax.swing.JLabel();
        cb_dueño1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        t_nombreP1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        t_edadP1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        rb_fP1 = new javax.swing.JRadioButton();
        rb_mP1 = new javax.swing.JRadioButton();
        jLabel48 = new javax.swing.JLabel();
        t_estadoCivilP1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        t_ocupacion1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        t_hE1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        t_hS1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        c_fechaP1 = new com.toedter.calendar.JDateChooser();
        bt_guardarP1 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        t_sueldoP1 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        t_contraseñaP1 = new javax.swing.JTextField();
        cb_personalModificar = new javax.swing.JComboBox<>();
        jLabel87 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Nuevo Contacto del Personal");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 169, 38));

        jLabel12.setText("Nombre");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 55, 62, 24));

        t_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombrePActionPerformed(evt);
            }
        });
        jPanel5.add(t_nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 57, 139, -1));

        jLabel13.setText("Edad");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 90, 62, 25));
        jPanel5.add(t_edadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 92, 63, -1));

        jLabel14.setText("Sexo");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 126, 43, 23));

        rb_grupoP.add(rb_fP);
        rb_fP.setText("F");
        jPanel5.add(rb_fP, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 126, -1, -1));

        rb_grupoP.add(rb_mP);
        rb_mP.setText("M");
        jPanel5.add(rb_mP, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 126, -1, -1));

        jLabel15.setText("Estado Civil");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 167, 65, 27));
        jPanel5.add(t_estadoCivilP, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 169, 136, 23));

        jLabel16.setText("Ocupación");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 212, 65, 25));
        jPanel5.add(t_ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 212, 178, 25));

        jLabel17.setText("Hora Entrada");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 268, 75, 25));
        jPanel5.add(t_hE, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 270, 84, -1));

        jLabel18.setText("Hora Salida");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 264, 73, 32));
        jPanel5.add(t_hS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 92, -1));

        jLabel19.setText("Fecha de Inicio  de Tranajo");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 330, 145, 23));

        c_fechaP.setDateFormatString("dd/MM/yyyy");
        jPanel5.add(c_fechaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 138, -1));

        bt_guardarP.setText("Guardar");
        bt_guardarP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bt_guardarPMouseDragged(evt);
            }
        });
        bt_guardarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarPMouseClicked(evt);
            }
        });
        bt_guardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarPActionPerformed(evt);
            }
        });
        jPanel5.add(bt_guardarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 364, 109, 35));

        jLabel40.setText("Sueldo");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 330, 90, 20));
        jPanel5.add(t_sueldoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 330, 91, -1));

        jLabel41.setText("Contraseña");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 173, 70, -1));
        jPanel5.add(t_contraseñaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, -1));

        jTabbedPane2.addTab("Personal", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Contacto Familiar");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, 38));

        jLabel2.setText("Nombre");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, 62, 24));

        t_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombreActionPerformed(evt);
            }
        });
        jPanel4.add(t_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 57, 139, -1));

        jLabel3.setText("Edad");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 62, 25));
        jPanel4.add(t_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 92, 63, -1));

        jLabel4.setText("Sexo");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 126, 43, 23));

        rb_grupo.add(rb_f);
        rb_f.setText("F");
        jPanel4.add(rb_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 126, -1, -1));

        rb_grupo.add(rb_m);
        rb_m.setText("M");
        jPanel4.add(rb_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 126, -1, -1));

        jLabel5.setText("Estado Civil");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 167, 65, 27));
        jPanel4.add(t_estadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 169, 136, 23));

        jLabel6.setText("Roll");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 168, 53, 25));

        cb_rolles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", "Hermana", "Hermano", "Esposo" }));
        jPanel4.add(cb_rolles, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 170, 110, -1));

        jLabel7.setText("Trabajo");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 230, 53, 29));
        jPanel4.add(t_trabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 232, 140, 24));

        jLabel8.setText("Altura");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 287, 53, 26));
        jPanel4.add(t_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 285, 83, 30));

        jLabel9.setText("Peso");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 285, 64, 30));
        jPanel4.add(t_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 285, 92, 30));

        jLabel10.setText("Objeto");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 345, 53, 27));

        jPanel4.add(cb_objetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 348, 104, -1));

        bt_guardarF.setText("Guardar");
        bt_guardarF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarFMouseClicked(evt);
            }
        });
        jPanel4.add(bt_guardarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 366, 97, 33));

        jLabel42.setText("Contraseña");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 234, 70, 20));

        t_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_contraseñaActionPerformed(evt);
            }
        });
        jPanel4.add(t_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 130, -1));

        jTabbedPane2.addTab("Familiar", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Nuevo Objeto");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 11, 134, 30));

        jLabel21.setText("Color");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, 50, 24));

        bt_color.setForeground(new java.awt.Color(0, 153, 153));
        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });
        jPanel6.add(bt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 59, 69, 24));

        jLabel22.setText("Descripcion");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 71, 20));

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 90, 50));

        jLabel23.setText("Marca");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, 20));
        jPanel6.add(t_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 90, 30));

        jLabel24.setText("Tamaño");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 60, 20));
        jPanel6.add(t_tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 70, 30));

        jLabel25.setText("Calidad");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 20));
        jPanel6.add(t_calidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 30));

        jLabel26.setText("Precio");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        jPanel6.add(t_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Para El Hogar");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Ropa");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Zapatos");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, 20));

        jLabel30.setText("Confort");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, 30));
        jPanel6.add(t_confort, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 60, -1));

        jLabel31.setText("Talla");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 40, 30));
        jPanel6.add(t_paisElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, -1));

        jLabel32.setText("Material");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 50, 30));

        t_suela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_suelaActionPerformed(evt);
            }
        });
        jPanel6.add(t_suela, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, -1));

        bt_Ropa.setText("Guardar");
        bt_Ropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_RopaMouseClicked(evt);
            }
        });
        jPanel6.add(bt_Ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel33.setText("Pais Elaboración");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 30));

        jLabel34.setText("Talla");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 30));
        jPanel6.add(t_tallaZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, -1));
        jPanel6.add(t_tiempoVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 60, -1));

        jLabel36.setText("Tipo Suela");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, 30));
        jPanel6.add(t_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 60, -1));

        bt_zapatos1.setText("Guardar");
        bt_zapatos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_zapatos1MouseClicked(evt);
            }
        });
        jPanel6.add(bt_zapatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel35.setText("Area en Casa");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, 20));
        jPanel6.add(t_tallaRopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 60, -1));

        jLabel37.setText("Tiempo Vida");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 70, 20));

        cb_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala", "Cocina", "Habitación" }));
        jPanel6.add(cb_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel38.setText("Instrucciones");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, 20));

        ta_descripcion1.setColumns(20);
        ta_descripcion1.setRows(5);
        jScrollPane2.setViewportView(ta_descripcion1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, 50));

        jLabel39.setText("Fecha");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 70, 20));

        c_fechaObjeto.setDateFormatString("dd/MM/yyyy");
        jPanel6.add(c_fechaObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, -1));

        bt_guardarHogar.setText("Guardar");
        bt_guardarHogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarHogarMouseClicked(evt);
            }
        });
        jPanel6.add(bt_guardarHogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jLabel43.setText("Dueño");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, 20));

        jPanel6.add(cb_dueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 100, -1));

        jTabbedPane2.addTab("Objeto", jPanel6);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Agregar", jPanel1);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setText("Nuevo Contacto Familiar");
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 169, 38));

        jLabel56.setText("Nombre");
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, 62, 24));

        t_nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombre1ActionPerformed(evt);
            }
        });
        jPanel8.add(t_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 57, 139, -1));

        jLabel57.setText("Edad");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 62, 25));
        jPanel8.add(t_edad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 92, 63, -1));

        jLabel58.setText("Sexo");
        jPanel8.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 126, 43, 23));

        rb_grupo.add(rb_f1);
        rb_f1.setText("F");
        jPanel8.add(rb_f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 126, -1, -1));

        rb_grupo.add(rb_m1);
        rb_m1.setText("M");
        jPanel8.add(rb_m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 126, -1, -1));

        jLabel59.setText("Estado Civil");
        jPanel8.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 167, 65, 27));
        jPanel8.add(t_estadoCivil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 169, 136, 23));

        jLabel60.setText("Roll");
        jPanel8.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 168, 53, 25));

        cb_rolles1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", "Hermana", "Hermano", "Esposo" }));
        jPanel8.add(cb_rolles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 170, 110, -1));

        jLabel61.setText("Trabajo");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 230, 53, 29));
        jPanel8.add(t_trabajo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 232, 140, 24));

        jLabel62.setText("Altura");
        jPanel8.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 287, 53, 26));
        jPanel8.add(t_altura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 285, 83, 30));

        jLabel63.setText("Peso");
        jPanel8.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 285, 64, 30));
        jPanel8.add(t_peso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 285, 92, 30));

        jLabel64.setText("Objeto");
        jPanel8.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 345, 53, 27));

        jPanel8.add(cb_objetos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 348, 104, -1));

        bt_guardarF1.setText("Guardar");
        bt_guardarF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarF1MouseClicked(evt);
            }
        });
        jPanel8.add(bt_guardarF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 366, 97, 33));

        jLabel65.setText("Contraseña");
        jPanel8.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 234, 70, 20));

        t_contraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_contraseña1ActionPerformed(evt);
            }
        });
        jPanel8.add(t_contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 130, -1));

        jTabbedPane3.addTab("Familiar", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setText("Nuevo Objeto");
        jPanel9.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 11, 134, 30));

        jLabel67.setText("Color");
        jPanel9.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, 50, 24));

        bt_color1.setForeground(new java.awt.Color(0, 153, 153));
        bt_color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_color1MouseClicked(evt);
            }
        });
        jPanel9.add(bt_color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 59, 69, 24));

        jLabel68.setText("Descripcion");
        jPanel9.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 71, 20));

        ta_descripcion2.setColumns(20);
        ta_descripcion2.setRows(5);
        jScrollPane3.setViewportView(ta_descripcion2);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 90, 50));

        jLabel69.setText("Marca");
        jPanel9.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, 20));
        jPanel9.add(t_marca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 90, 30));

        jLabel70.setText("Tamaño");
        jPanel9.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 60, 20));
        jPanel9.add(t_tamano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 70, 30));

        jLabel71.setText("Calidad");
        jPanel9.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 20));
        jPanel9.add(t_calidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 30));

        jLabel72.setText("Precio");
        jPanel9.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        jPanel9.add(t_precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setText("Para El Hogar");
        jPanel9.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 20));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setText("Ropa");
        jPanel9.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, 20));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel75.setText("Zapatos");
        jPanel9.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, 20));

        jLabel76.setText("Confort");
        jPanel9.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, 30));
        jPanel9.add(t_confort1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 60, -1));

        jLabel77.setText("Talla");
        jPanel9.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 40, 30));
        jPanel9.add(t_paisElaboracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, -1));

        jLabel78.setText("Material");
        jPanel9.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 50, 30));

        t_suela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_suela1ActionPerformed(evt);
            }
        });
        jPanel9.add(t_suela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, -1));

        bt_Ropa1.setText("Guardar");
        bt_Ropa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Ropa1MouseClicked(evt);
            }
        });
        jPanel9.add(bt_Ropa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel79.setText("Pais Elaboración");
        jPanel9.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 30));

        jLabel80.setText("Talla");
        jPanel9.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 30));
        jPanel9.add(t_tallaZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, -1));
        jPanel9.add(t_tiempoVida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 60, -1));

        jLabel81.setText("Tipo Suela");
        jPanel9.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, 30));
        jPanel9.add(t_material1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 60, -1));

        bt_zapatos2.setText("Guardar");
        bt_zapatos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_zapatos2MouseClicked(evt);
            }
        });
        jPanel9.add(bt_zapatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel82.setText("Area en Casa");
        jPanel9.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, 20));
        jPanel9.add(t_tallaRopa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 60, -1));

        jLabel83.setText("Tiempo Vida");
        jPanel9.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 70, 20));

        cb_area1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala", "Cocina", "Habitación" }));
        jPanel9.add(cb_area1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel84.setText("Instrucciones");
        jPanel9.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, 20));

        ta_descripcion3.setColumns(20);
        ta_descripcion3.setRows(5);
        jScrollPane4.setViewportView(ta_descripcion3);

        jPanel9.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, 50));

        jLabel85.setText("Fecha");
        jPanel9.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 70, 20));

        c_fechaObjeto1.setDateFormatString("dd/MM/yyyy");
        jPanel9.add(c_fechaObjeto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, -1));

        bt_guardarHogar1.setText("Guardar");
        bt_guardarHogar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarHogar1MouseClicked(evt);
            }
        });
        jPanel9.add(bt_guardarHogar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jLabel86.setText("Dueño");
        jPanel9.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, 20));

        jPanel9.add(cb_dueño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 100, -1));

        jTabbedPane3.addTab("Objeto", jPanel9);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setText("Modificar Pesonal");
        jPanel7.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 38));

        jLabel45.setText("Nombre");
        jPanel7.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 55, 62, 24));

        t_nombreP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombreP1ActionPerformed(evt);
            }
        });
        jPanel7.add(t_nombreP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 57, 139, -1));

        jLabel46.setText("Edad");
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 90, 62, 25));
        jPanel7.add(t_edadP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 92, 63, -1));

        jLabel47.setText("Sexo");
        jPanel7.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 126, 43, 23));

        rb_grupoP.add(rb_fP1);
        rb_fP1.setSelected(true);
        rb_fP1.setText("F");
        jPanel7.add(rb_fP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 126, -1, -1));

        rb_grupoP.add(rb_mP1);
        rb_mP1.setText("M");
        jPanel7.add(rb_mP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 126, -1, -1));

        jLabel48.setText("Estado Civil");
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 167, 65, 27));
        jPanel7.add(t_estadoCivilP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 169, 136, 23));

        jLabel49.setText("Ocupación");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 212, 65, 25));
        jPanel7.add(t_ocupacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 212, 178, 25));

        jLabel50.setText("Hora Entrada");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 268, 75, 25));
        jPanel7.add(t_hE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 270, 84, -1));

        jLabel51.setText("Hora Salida");
        jPanel7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 264, 73, 32));
        jPanel7.add(t_hS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 92, -1));

        jLabel52.setText("Fecha de Inicio  de Tranajo");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 330, 145, 23));

        c_fechaP1.setDateFormatString("dd/MM/yyyy");
        jPanel7.add(c_fechaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 138, -1));

        bt_guardarP1.setText("Guardar");
        bt_guardarP1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bt_guardarP1MouseDragged(evt);
            }
        });
        bt_guardarP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarP1MouseClicked(evt);
            }
        });
        jPanel7.add(bt_guardarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 364, 109, 35));

        jLabel53.setText("Sueldo");
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 330, 90, 20));
        jPanel7.add(t_sueldoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 330, 91, -1));

        jLabel54.setText("Contraseña");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 173, 70, -1));
        jPanel7.add(t_contraseñaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, -1));

        cb_personalModificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_personalModificarItemStateChanged(evt);
            }
        });
        cb_personalModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_personalModificarMouseClicked(evt);
            }
        });
        cb_personalModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_personalModificarActionPerformed(evt);
            }
        });
        jPanel7.add(cb_personalModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 170, 30));

        jLabel87.setText("Personal");
        jPanel7.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 90, 20));

        jTabbedPane3.addTab("Personal", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombreActionPerformed

    private void t_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombrePActionPerformed

    private void bt_guardarPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarPMouseDragged


    }//GEN-LAST:event_bt_guardarPMouseDragged

    private void bt_guardarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarPMouseClicked
        // TODO add your handling code here:
        String nombre;
        int edad;
        int idP;
        String sexo;
        String estado_civil;
        String ocupacion;
        String horario;
        int tiempo_trabajando;
        String contraseña;
        double sueldo;
        try {
            nombre = t_nombreP.getText();
            edad = Integer.parseInt(t_edadP.getText());
            idP = id;
            id++;
            if (rb_fP.isSelected()) {
                sexo = "F";
            } else {
                sexo = "M";
            }

            estado_civil = t_estadoCivilP.getText();
            ocupacion = t_ocupacion.getText();
            horario = t_hE.getText() + "-" + t_hS.getText();
            // long n = ((new Date()).getTime() -  (c_fechaP.getDate()).getTime() ) /(1000 * 60 * 60) ;
            tiempo_trabajando = Integer.parseInt("" + ((new Date()).getTime() - (c_fechaP.getDate()).getTime()) / (1000 * 60 * 60));
            sueldo = Double.parseDouble(t_sueldoP.getText());
            contraseña = t_contraseñaP.getText();

            personas.add(new Personal(ocupacion, horario, tiempo_trabajando, sueldo, nombre, edad, id, sexo, estado_civil, contraseña));
            System.out.println(personas.get(personas.size() - 1));
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_personalModificar.getModel(); // capturamos la vista del modelo
            modelo.addElement(personas.get(personas.size() - 1));
            cb_personalModificar.setModel(modelo); // refrescamos
            t_nombreP.setText("");
            t_edadP.setText("");
            rb_fP.setSelected(true);
            rb_mP.setSelected(false);
            t_estadoCivilP.setText("");
            t_ocupacion.setText("");
            t_hE.setText("");
            t_hS.setText("");
            c_fechaP.setDate(new Date());
            t_sueldoP.setText("");
            t_contraseñaP.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Fatal, Reinicie su computadora!!");
        }

    }//GEN-LAST:event_bt_guardarPMouseClicked

    private void t_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_contraseñaActionPerformed

    private void bt_guardarFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarFMouseClicked
        String nombre;
        int edad;
        int idF;
        String sexo;
        String estado_civil;
        String contraseña;
        String rol = "";
        String trabajo;
        double altura;
        double peso;

        try {
            nombre = t_nombre.getText();
            edad = Integer.parseInt(t_edad.getText());
            idF = id;
            id++;
            if (rb_f.isSelected()) {
                sexo = "F";
            } else {
                sexo = "M";
            }

            estado_civil = t_estadoCivil.getText();
            contraseña = t_contraseña.getText();
            trabajo = t_trabajo.getText();
            altura = Double.parseDouble(t_altura.getText());
            peso = Double.parseDouble(t_peso.getText());

            if (cb_rolles.getSelectedItem().toString().equals("Madre") && madre == 0) {
                madre++;
                rol = cb_rolles.getSelectedItem().toString();
            } else if (cb_rolles.getSelectedItem().toString().equals("Padre") && padre == 0) {
                padre++;
                rol = cb_rolles.getSelectedItem().toString();
            } else if (cb_rolles.getSelectedItem().toString().equals("Hermana") && hermanas <= 4) {
                hermanas++;
                rol = cb_rolles.getSelectedItem().toString();
            } else if (cb_rolles.getSelectedItem().toString().equals("Hermano") && hermano == 0) {
                hermano++;
                rol = cb_rolles.getSelectedItem().toString();
            } else if (cb_rolles.getSelectedItem().toString().equals("Esposo") && esposo == 0) {
                esposo++;
                rol = cb_rolles.getSelectedItem().toString();
            }

            if (rol.length() > 0) {
                personas.add(new Familiar(rol, trabajo, altura, peso, nombre, edad, idF, sexo, estado_civil, contraseña));
                idF++;
                System.out.println(personas.get(personas.size() - 1));
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_dueño.getModel(); // capturamos la vista del modelo
                modelo.addElement(personas.get(personas.size() - 1));
                cb_dueño.setModel(modelo); // refrescamos

            } else {
                JOptionPane.showMessageDialog(null, "Es posible que ya no se puedad agregar usuarios con ese roll");
            }

            t_nombre.setText("");
            t_edad.setText("");
            rb_f.setSelected(true);
            rb_m.setSelected(false);
            t_estadoCivil.setText("");
            t_contraseña.setText("");
            t_trabajo.setText("");
            t_altura.setText("");
            t_peso.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Fatal, Reinicie su computadora!!");
        }
    }//GEN-LAST:event_bt_guardarFMouseClicked

    private void bt_zapatos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_zapatos1MouseClicked
        Color color;
        String descripcion;
        String marca;
        int tamano;
        int calidad;
        double precio;
        String dueño;
        int talla;
        String suela;
        int confort;
        try {
            color = bt_color.getBackground();
            descripcion = ta_descripcion1.getText();
            marca = t_marca.getText();
            tamano = Integer.parseInt(t_tamano.getText());
            calidad = Integer.parseInt(t_calidad.getText());
            precio = Double.parseDouble(t_precio.getText());
            dueño = cb_dueño.getSelectedItem().toString();
            talla = Integer.parseInt(t_tallaZ.getText());
            suela = t_suela.getText();
            confort = Integer.parseInt(t_confort.getText());

            objetos.add(new Zapatos(talla, suela, confort, color, descripcion, marca, tamano, calidad, precio, dueño));
            System.out.println(objetos.get(objetos.size() - 1));
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_objetos.getModel(); // capturamos la vista del modelo
            modelo.addElement(objetos.get(objetos.size() - 1));
            cb_objetos.setModel(modelo); // refrescamos

            bt_color.setBackground(color.red);
            ta_descripcion1.setText("");
            t_marca.setText("");
            t_tamano.setText("");
            t_calidad.setText("");
            t_precio.setText("");
            t_tallaZ.setText("");
            t_suela.setText("");
            t_confort.setText("");

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Error, no se guardaron los datos");

        }

    }//GEN-LAST:event_bt_zapatos1MouseClicked

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        bt_color.setBackground(JColorChooser.showDialog(this, "Seleccione color", Color.yellow));
    }//GEN-LAST:event_bt_colorMouseClicked

    private void bt_RopaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RopaMouseClicked
        Color color;
        String descripcion;
        String marca;
        int tamano;
        int calidad;
        double precio;
        String dueño;
        String talla;
        String material;
        String pais;

        try {
            color = bt_color.getBackground();
            descripcion = ta_descripcion1.getText();
            marca = t_marca.getText();
            tamano = Integer.parseInt(t_tamano.getText());
            calidad = Integer.parseInt(t_calidad.getText());
            precio = Double.parseDouble(t_precio.getText());
            dueño = cb_dueño.getSelectedItem().toString();
            talla = t_tallaRopa.getText();
            material = t_material.getText();
            pais = t_paisElaboracion.getText();

            objetos.add(new Ropa(talla, material, pais, color, descripcion, marca, tamano, calidad, precio, dueño));
            System.out.println(objetos.get(objetos.size() - 1));
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_objetos.getModel(); // capturamos la vista del modelo
            modelo.addElement(objetos.get(objetos.size() - 1));
            cb_objetos.setModel(modelo); // refrescamos

            bt_color.setBackground(color.red);
            ta_descripcion1.setText("");
            t_marca.setText("");
            t_tamano.setText("");
            t_calidad.setText("");
            t_tallaRopa.setText("");
            t_material.setText("");
            t_paisElaboracion.setText("");

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Error, no se guardaron los datos");

        }
    }//GEN-LAST:event_bt_RopaMouseClicked

    private void bt_guardarHogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarHogarMouseClicked
        Color color;
        String descripcion;
        String marca;
        int tamano;
        int calidad;
        double precio;
        String dueño;
        int tiempo;
        String area;
        String instruccion;
        Date fecha;

        try {
            color = bt_color.getBackground();
            descripcion = ta_descripcion1.getText();
            marca = t_marca.getText();
            tamano = Integer.parseInt(t_tamano.getText());
            calidad = Integer.parseInt(t_calidad.getText());
            precio = Double.parseDouble(t_precio.getText());
            dueño = cb_dueño.getSelectedItem().toString();
            tiempo = Integer.parseInt(t_tiempoVida.getText());
            area = cb_area.getSelectedItem().toString();
            instruccion = ta_descripcion.getText();
            fecha = c_fechaObjeto.getDate();

            objetos.add(new ObjetoHogar(tiempo, area, instruccion, fecha, color, descripcion, marca, tamano, calidad, precio, dueño));
            System.out.println(objetos.get(objetos.size() - 1));
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_objetos.getModel(); // capturamos la vista del modelo
            modelo.addElement(objetos.get(objetos.size() - 1));
            cb_objetos.setModel(modelo); // refrescamos

            bt_color.setBackground(color.red);
            ta_descripcion1.setText("");
            t_marca.setText("");
            t_tamano.setText("");
            t_calidad.setText("");
            t_tiempoVida.setText("");
            ta_descripcion.setText("");
            c_fechaObjeto.setDate(new Date());

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Error, no se guardaron los datos");

        }
    }//GEN-LAST:event_bt_guardarHogarMouseClicked

    private void t_suelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_suelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_suelaActionPerformed

    private void t_nombreP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombreP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombreP1ActionPerformed

    private void bt_guardarP1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarP1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_guardarP1MouseDragged

    private void bt_guardarP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarP1MouseClicked
        try {
            seleccionado.setContraseña(t_contraseña1.getText());
            seleccionado.setEdad(Integer.parseInt(t_edad1.getText()));
            seleccionado.setHorario(t_hE1.getText() + "-" + t_hS1.getText());
            seleccionado.setEstado_civil(t_estadoCivil1.getText());
            seleccionado.setNombre(t_nombre1.getText());
            seleccionado.setOcupacion(t_ocupacion1.getText());
            if (rb_f1.isSelected()) {
                seleccionado.setSexo("F");
            } else {
                seleccionado.setSexo("M");
            }

            seleccionado.setSueldo(Double.parseDouble(t_sueldoP1.getText()));
            seleccionado.setTiempo_trabajando(Integer.parseInt("" + ((new Date()).getTime() - (c_fechaP1.getDate()).getTime()) / (1000 * 60 * 60)));

            
            for (int i = 0; i < personas.size(); i++) {
                if (personas.get(i).getId() == seleccionado.getId()) {
                    personas.remove(i);
                    personas.add(seleccionado);
                    DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_personalModificar.getModel(); // capturamos la vista del modelo
                    modelo.addElement(personas.get(personas.size() - 1));
                    cb_personalModificar.setModel(modelo); // refrescamos
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Asegurece de estar ingresando correctamente los datos");
        }
        


    }//GEN-LAST:event_bt_guardarP1MouseClicked

    private void t_nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombre1ActionPerformed

    private void bt_guardarF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarF1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_guardarF1MouseClicked

    private void t_contraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_contraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_contraseña1ActionPerformed

    private void bt_color1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_color1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_color1MouseClicked

    private void t_suela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_suela1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_suela1ActionPerformed

    private void bt_Ropa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Ropa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_Ropa1MouseClicked

    private void bt_zapatos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_zapatos2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_zapatos2MouseClicked

    private void bt_guardarHogar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarHogar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_guardarHogar1MouseClicked

    private void cb_personalModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_personalModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_personalModificarActionPerformed

    private void bt_guardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_guardarPActionPerformed

    private void cb_personalModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_personalModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_personalModificarMouseClicked

    private void cb_personalModificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_personalModificarItemStateChanged
        if (evt.getStateChange() == 1) {
            seleccionado = (Personal) cb_personalModificar.getSelectedItem();
            this.t_nombreP1.setText(seleccionado.getNombre());
            this.t_edadP1.setText("" + seleccionado.getEdad());
            String sexo = seleccionado.getSexo();
            if (sexo.equals("F")) {
                this.rb_fP1.setSelected(true);
            } else {
                this.rb_mP.setSelected(true);
            }

            this.t_estadoCivilP1.setText(seleccionado.getEstado_civil());
            this.t_ocupacion1.setText(seleccionado.getOcupacion());
            String array[] = seleccionado.getHorario().split("-");
            this.t_hE1.setText("" + array[0]);
            this.t_hS1.setText("" + array[1]);
            this.c_fechaP1.setDate(new Date());
            this.t_sueldoP1.setText("" + seleccionado.getSueldo());
            this.t_contraseñaP1.setText("" + seleccionado.getContraseña());
        }
    }//GEN-LAST:event_cb_personalModificarItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Ropa;
    private javax.swing.JButton bt_Ropa1;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_color1;
    private javax.swing.JButton bt_guardarF;
    private javax.swing.JButton bt_guardarF1;
    private javax.swing.JButton bt_guardarHogar;
    private javax.swing.JButton bt_guardarHogar1;
    private javax.swing.JButton bt_guardarP;
    private javax.swing.JButton bt_guardarP1;
    private javax.swing.JButton bt_zapatos1;
    private javax.swing.JButton bt_zapatos2;
    private com.toedter.calendar.JDateChooser c_fechaObjeto;
    private com.toedter.calendar.JDateChooser c_fechaObjeto1;
    private com.toedter.calendar.JDateChooser c_fechaP;
    private com.toedter.calendar.JDateChooser c_fechaP1;
    private javax.swing.JComboBox<String> cb_area;
    private javax.swing.JComboBox<String> cb_area1;
    private javax.swing.JComboBox<String> cb_dueño;
    private javax.swing.JComboBox<String> cb_dueño1;
    private javax.swing.JComboBox<String> cb_objetos;
    private javax.swing.JComboBox<String> cb_objetos1;
    private javax.swing.JComboBox<String> cb_personalModificar;
    private javax.swing.JComboBox<String> cb_rolles;
    private javax.swing.JComboBox<String> cb_rolles1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_f1;
    private javax.swing.JRadioButton rb_fP;
    private javax.swing.JRadioButton rb_fP1;
    private javax.swing.ButtonGroup rb_grupo;
    private javax.swing.ButtonGroup rb_grupoP;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_m1;
    private javax.swing.JRadioButton rb_mP;
    private javax.swing.JRadioButton rb_mP1;
    private javax.swing.JTextField t_altura;
    private javax.swing.JTextField t_altura1;
    private javax.swing.JTextField t_calidad;
    private javax.swing.JTextField t_calidad1;
    private javax.swing.JTextField t_confort;
    private javax.swing.JTextField t_confort1;
    private javax.swing.JTextField t_contraseña;
    private javax.swing.JTextField t_contraseña1;
    private javax.swing.JTextField t_contraseñaP;
    private javax.swing.JTextField t_contraseñaP1;
    private javax.swing.JTextField t_edad;
    private javax.swing.JTextField t_edad1;
    private javax.swing.JTextField t_edadP;
    private javax.swing.JTextField t_edadP1;
    private javax.swing.JTextField t_estadoCivil;
    private javax.swing.JTextField t_estadoCivil1;
    private javax.swing.JTextField t_estadoCivilP;
    private javax.swing.JTextField t_estadoCivilP1;
    private javax.swing.JTextField t_hE;
    private javax.swing.JTextField t_hE1;
    private javax.swing.JTextField t_hS;
    private javax.swing.JTextField t_hS1;
    private javax.swing.JTextField t_marca;
    private javax.swing.JTextField t_marca1;
    private javax.swing.JTextField t_material;
    private javax.swing.JTextField t_material1;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_nombre1;
    private javax.swing.JTextField t_nombreP;
    private javax.swing.JTextField t_nombreP1;
    private javax.swing.JTextField t_ocupacion;
    private javax.swing.JTextField t_ocupacion1;
    private javax.swing.JTextField t_paisElaboracion;
    private javax.swing.JTextField t_paisElaboracion1;
    private javax.swing.JTextField t_peso;
    private javax.swing.JTextField t_peso1;
    private javax.swing.JTextField t_precio;
    private javax.swing.JTextField t_precio1;
    private javax.swing.JTextField t_suela;
    private javax.swing.JTextField t_suela1;
    private javax.swing.JTextField t_sueldoP;
    private javax.swing.JTextField t_sueldoP1;
    private javax.swing.JTextField t_tallaRopa;
    private javax.swing.JTextField t_tallaRopa1;
    private javax.swing.JTextField t_tallaZ;
    private javax.swing.JTextField t_tallaZ1;
    private javax.swing.JTextField t_tamano;
    private javax.swing.JTextField t_tamano1;
    private javax.swing.JTextField t_tiempoVida;
    private javax.swing.JTextField t_tiempoVida1;
    private javax.swing.JTextField t_trabajo;
    private javax.swing.JTextField t_trabajo1;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextArea ta_descripcion1;
    private javax.swing.JTextArea ta_descripcion2;
    private javax.swing.JTextArea ta_descripcion3;
    // End of variables declaration//GEN-END:variables

    ArrayList<Persona> personas = new ArrayList();
    ArrayList<Objeto> objetos = new ArrayList();
    int madre = 0;
    int padre = 0;
    int hermanas = 0;
    int hermano = 0;
    int esposo = 0, id = 0;
    Personal seleccionado;

}// fin
