
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 1234
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_grupo = new javax.swing.ButtonGroup();
        rb_grupoP = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_nombreP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t_edadP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rb_fP = new javax.swing.JRadioButton();
        rb_mP = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        t_estadoCivilP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t_ocupacion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_hE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t_hS = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        c_fechaP = new com.toedter.calendar.JDateChooser();
        bt_guardarP = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        t_sueldoP = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        t_contraseñaP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rb_f = new javax.swing.JRadioButton();
        rb_m = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        t_estadoCivil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_rolles = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        t_trabajo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_altura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_peso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_objetos = new javax.swing.JComboBox<>();
        bt_guardarF = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        t_contraseña = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bt_color = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        t_marca = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t_tamano = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        t_precio = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        t_confort = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        t_paisElaboracion = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        t_suela1 = new javax.swing.JTextField();
        bt_Ropa = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        t_talla2 = new javax.swing.JTextField();
        t_tiempoVida = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        t_tallaRopa2 = new javax.swing.JTextField();
        bt_zapatos1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        t_tallaRopa3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_descripcion1 = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        c_fechaObjeto = new com.toedter.calendar.JDateChooser();
        bt_guardarHogar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Nuevo Contacto del Personal");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 169, 38));

        jLabel12.setText("Nombre");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 55, 62, 24));

        t_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombrePActionPerformed(evt);
            }
        });
        jPanel5.add(t_nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 57, 139, -1));

        jLabel13.setText("Edad");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 90, 62, 25));
        jPanel5.add(t_edadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 92, 63, -1));

        jLabel14.setText("Sexo");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 126, 43, 23));

        rb_grupoP.add(rb_fP);
        rb_fP.setSelected(true);
        rb_fP.setText("F");
        jPanel5.add(rb_fP, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 126, -1, -1));

        rb_grupoP.add(rb_mP);
        rb_mP.setText("M");
        jPanel5.add(rb_mP, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 126, -1, -1));

        jLabel15.setText("Estado Civil");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 167, 65, 27));
        jPanel5.add(t_estadoCivilP, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 169, 136, 23));

        jLabel16.setText("Ocupación");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 212, 65, 25));
        jPanel5.add(t_ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 212, 178, 25));

        jLabel17.setText("Hora Entrada");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 268, 75, 25));
        jPanel5.add(t_hE, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 270, 84, -1));

        jLabel18.setText("Hora Salida");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 264, 73, 32));
        jPanel5.add(t_hS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 92, -1));

        jLabel19.setText("Fecha de Inicio  de Tranajo");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 330, 145, 23));

        c_fechaP.setDateFormatString("dd/MM/yyyy");
        jPanel5.add(c_fechaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 138, -1));

        bt_guardarP.setText("Guardar");
        bt_guardarP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bt_guardarPMouseDragged(evt);
            }
        });
        bt_guardarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarPMouseClicked(evt);
            }
        });
        jPanel5.add(bt_guardarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 364, 109, 35));

        jLabel40.setText("Sueldo");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 330, 90, 20));
        jPanel5.add(t_sueldoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 330, 91, -1));

        jLabel41.setText("Contraseña");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 173, 70, -1));
        jPanel5.add(t_contraseñaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, -1));

        jTabbedPane2.addTab("Personal", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Contacto Familiar");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 169, 38));

        jLabel2.setText("Nombre");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, 62, 24));

        t_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombreActionPerformed(evt);
            }
        });
        jPanel4.add(t_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 57, 139, -1));

        jLabel3.setText("Edad");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 62, 25));
        jPanel4.add(t_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 92, 63, -1));

        jLabel4.setText("Sexo");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 126, 43, 23));

        rb_grupo.add(rb_f);
        rb_f.setText("F");
        jPanel4.add(rb_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 126, -1, -1));

        rb_grupo.add(rb_m);
        rb_m.setText("M");
        jPanel4.add(rb_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 126, -1, -1));

        jLabel5.setText("Estado Civil");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 167, 65, 27));
        jPanel4.add(t_estadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 169, 136, 23));

        jLabel6.setText("Roll");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 168, 53, 25));

        cb_rolles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", "Hermana", "Hermano", "Esposo" }));
        jPanel4.add(cb_rolles, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 170, 110, -1));

        jLabel7.setText("Trabajo");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 230, 53, 29));
        jPanel4.add(t_trabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 232, 140, 24));

        jLabel8.setText("Altura");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 287, 53, 26));
        jPanel4.add(t_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 285, 83, 30));

        jLabel9.setText("Peso");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 285, 64, 30));
        jPanel4.add(t_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 285, 92, 30));

        jLabel10.setText("Objeto");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 345, 53, 27));

        jPanel4.add(cb_objetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 348, 104, -1));

        bt_guardarF.setText("Guardar");
        bt_guardarF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarFMouseClicked(evt);
            }
        });
        jPanel4.add(bt_guardarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 366, 97, 33));

        jLabel42.setText("Contraseña");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 234, 70, 20));

        t_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_contraseñaActionPerformed(evt);
            }
        });
        jPanel4.add(t_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 130, -1));

        jTabbedPane2.addTab("Familiar", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Nuevo Objeto");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 11, 134, 30));

        jLabel21.setText("Color");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, 50, 24));
        jPanel6.add(bt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 59, 69, 24));

        jLabel22.setText("Descripcion");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 71, 20));

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 90, 50));

        jLabel23.setText("Marca");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, 20));
        jPanel6.add(t_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 20));

        jLabel24.setText("Tamaño");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 60, 20));
        jPanel6.add(t_tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 70, 20));

        jLabel25.setText("Calidad");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 20));
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, -1));

        jLabel26.setText("Precio");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        jPanel6.add(t_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Para El Hogar");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Ropa");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Zapatos");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, 20));

        jLabel30.setText("Confort");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, 30));
        jPanel6.add(t_confort, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 60, -1));

        jLabel31.setText("Talla");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 40, 30));
        jPanel6.add(t_paisElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, -1));

        jLabel32.setText("Material");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 50, 30));
        jPanel6.add(t_suela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, -1));

        bt_Ropa.setText("Guardar");
        jPanel6.add(bt_Ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel33.setText("Pais Elaboración");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 30));

        jLabel34.setText("Talla");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 30));
        jPanel6.add(t_talla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, -1));
        jPanel6.add(t_tiempoVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 60, -1));

        jLabel36.setText("Tipo Suela");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, 30));
        jPanel6.add(t_tallaRopa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 60, -1));

        bt_zapatos1.setText("Guardar");
        jPanel6.add(bt_zapatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel35.setText("Area en Casa");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, 20));
        jPanel6.add(t_tallaRopa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 60, -1));

        jLabel37.setText("Tiempo Vida");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 70, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala", "Cocina", "Habitación" }));
        jPanel6.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel38.setText("Instrucciones");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, 20));

        ta_descripcion1.setColumns(20);
        ta_descripcion1.setRows(5);
        jScrollPane2.setViewportView(ta_descripcion1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, 50));

        jLabel39.setText("Fecha");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 70, 20));

        c_fechaObjeto.setDateFormatString("dd/MM/yyyy");
        jPanel6.add(c_fechaObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, -1));

        bt_guardarHogar.setText("Guardar");
        jPanel6.add(bt_guardarHogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jTabbedPane2.addTab("Objeto", jPanel6);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Agregar", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombreActionPerformed

    private void t_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombrePActionPerformed

    private void bt_guardarPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarPMouseDragged


    }//GEN-LAST:event_bt_guardarPMouseDragged

    private void bt_guardarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarPMouseClicked
        // TODO add your handling code here:
        String nombre;
        int edad;
        int idP;
        String sexo;
        String estado_civil;
        String ocupacion;
        String horario;
        int tiempo_trabajando;
        String contraseña;
        double sueldo;
        try {
            nombre = t_nombreP.getText();
            edad = Integer.parseInt(t_edadP.getText());
            idP = id;
            id++;
            if (rb_fP.isSelected()) {
                sexo = "F";
            } else {
                sexo = "M";
            }

            estado_civil = t_estadoCivilP.getText();
            ocupacion = t_ocupacion.getText();
            horario = t_hE.getText() + "-" + t_hS.getText();
            // long n = ((new Date()).getTime() -  (c_fechaP.getDate()).getTime() ) /(1000 * 60 * 60) ;
            tiempo_trabajando = Integer.parseInt("" + ((new Date()).getTime() - (c_fechaP.getDate()).getTime()) / (1000 * 60 * 60));
            sueldo = Double.parseDouble(t_sueldoP.getText());
            contraseña = t_contraseñaP.getText();

            personas.add(new Personal(ocupacion, horario, tiempo_trabajando, sueldo, nombre, edad, id, sexo, estado_civil, contraseña));
            System.out.println(personas.get(personas.size() - 1));
            t_nombreP.setText("");
            t_edadP.setText("");
            rb_fP.setSelected(true);
            rb_mP.setSelected(false);
            t_estadoCivilP.setText("");
            t_ocupacion.setText("");
            t_hE.setText("");
            t_hS.setText("");
            c_fechaP.setDate(new Date());
            t_sueldoP.setText("");
            t_contraseñaP.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Fatal, Reinicie su computadora!!");
        }

    }//GEN-LAST:event_bt_guardarPMouseClicked

    private void t_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_contraseñaActionPerformed

    private void bt_guardarFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarFMouseClicked
        String nombre;
        int edad;
        int idF;
        String sexo;
        String estado_civil;
        String contraseña;
        String rol = "";
        String trabajo;
        double altura;
        double peso;

        try {
            nombre = t_nombre.getText();
            edad = Integer.parseInt(t_edad.getText());
            idF = id;
            id++;
            if (rb_f.isSelected()) {
                sexo = "F";
            } else {
                sexo = "M";
            }

            estado_civil = t_estadoCivil.getText();
           contraseña = t_contraseña.getText();
           trabajo = t_trabajo.getText();
           altura = Double.parseDouble(t_altura.getText());
           peso = Double.parseDouble(t_peso.getText());
           
           if(cb_rolles.getSelectedItem().toString().equals("Madre") && madre == 0){
               madre++;
               rol = cb_rolles.getSelectedItem().toString();
           }else if(cb_rolles.getSelectedItem().toString().equals("Padre") && padre == 0){
               padre++;
               rol = cb_rolles.getSelectedItem().toString();
           }else if(cb_rolles.getSelectedItem().toString().equals("Hermana") && hermanas <= 4){
               hermanas++;
                rol = cb_rolles.getSelectedItem().toString();
           }else if(cb_rolles.getSelectedItem().toString().equals("Hermano") && hermano ==0){
               hermano++;
               rol = cb_rolles.getSelectedItem().toString();
           }else if(cb_rolles.getSelectedItem().toString().equals("Esposo") && esposo ==0){
               esposo++;
               rol = cb_rolles.getSelectedItem().toString();
           }
            
           if(rol.length()>0){
               personas.add(new Familiar(rol, trabajo, altura, peso, nombre, edad, idF, sexo, estado_civil, contraseña));
               idF++;
               System.out.println(personas.get(personas.size()-1));
           }else{
               JOptionPane.showMessageDialog(null, "Es posible que ya no se puedad agregar usuarios con ese roll");
           }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Fatal, Reinicie su computadora!!");
        }
    }//GEN-LAST:event_bt_guardarFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Ropa;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_guardarF;
    private javax.swing.JButton bt_guardarHogar;
    private javax.swing.JButton bt_guardarP;
    private javax.swing.JButton bt_zapatos1;
    private com.toedter.calendar.JDateChooser c_fechaObjeto;
    private com.toedter.calendar.JDateChooser c_fechaP;
    private javax.swing.JComboBox<String> cb_objetos;
    private javax.swing.JComboBox<String> cb_rolles;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_fP;
    private javax.swing.ButtonGroup rb_grupo;
    private javax.swing.ButtonGroup rb_grupoP;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_mP;
    private javax.swing.JTextField t_altura;
    private javax.swing.JTextField t_confort;
    private javax.swing.JTextField t_contraseña;
    private javax.swing.JTextField t_contraseñaP;
    private javax.swing.JTextField t_edad;
    private javax.swing.JTextField t_edadP;
    private javax.swing.JTextField t_estadoCivil;
    private javax.swing.JTextField t_estadoCivilP;
    private javax.swing.JTextField t_hE;
    private javax.swing.JTextField t_hS;
    private javax.swing.JTextField t_marca;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_nombreP;
    private javax.swing.JTextField t_ocupacion;
    private javax.swing.JTextField t_paisElaboracion;
    private javax.swing.JTextField t_peso;
    private javax.swing.JTextField t_precio;
    private javax.swing.JTextField t_suela1;
    private javax.swing.JTextField t_sueldoP;
    private javax.swing.JTextField t_talla2;
    private javax.swing.JTextField t_tallaRopa2;
    private javax.swing.JTextField t_tallaRopa3;
    private javax.swing.JTextField t_tamano;
    private javax.swing.JTextField t_tiempoVida;
    private javax.swing.JTextField t_trabajo;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextArea ta_descripcion1;
    // End of variables declaration//GEN-END:variables

    ArrayList<Persona> personas = new ArrayList();
    int madre = 0;
    int padre = 0;
    int hermanas = 0;
    int hermano = 0;
    int esposo = 0, id = 0;

}// fin
